import os
from sqlite3 import connect as sqlite_connect

import psycopg

DB_NAME = os.getenv("DATABASE_PATH", "expenses.db")


def check_database():
    connection = get_connection()

    try:
        connection.execute("SELECT 1")
    finally:
        connection.close()


def get_connection():
    database_url = os.getenv("DATABASE_URL")

    if database_url:
        return psycopg.connect(database_url)

    return sqlite_connect(DB_NAME)


def init_db():
    connection = get_connection()

    if os.getenv("DATABASE_URL"):
        connection.execute("""
            CREATE TABLE IF NOT EXISTS expenses (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                amount REAL NOT NULL,
                category TEXT NOT NULL,
                name TEXT NOT NULL
            )
        """)
    else:
        connection.execute("""
            CREATE TABLE IF NOT EXISTS expenses (
                id INTEGER PRIMARY KEY,
                amount REAL NOT NULL,
                category TEXT NOT NULL,
                name TEXT NOT NULL
            )
        """)

    connection.commit()
    connection.close()


def create_expense(amount, category, name):
    connection = get_connection()

    if os.getenv("DATABASE_URL"):
        cursor = connection.execute(
            """
            INSERT INTO expenses (amount, category, name)
            VALUES (%s, %s, %s)
            RETURNING id
            """,
            (amount, category, name),
        )
        expense_id = cursor.fetchone()[0]
    else:
        cursor = connection.execute(
            "INSERT INTO expenses (amount, category, name) VALUES (?, ?, ?)",
            (amount, category, name),
        )
        expense_id = cursor.lastrowid

    connection.commit()
    connection.close()

    return expense_id


def get_expenses(
    category=None,
    name=None,
    name_contains=None,
    min_amount=None,
    max_amount=None,
    sort=None,
    limit=None,
    offset=None,
):
    connection = get_connection()

    placeholder = "%s" if os.getenv("DATABASE_URL") else "?"

    conditions = []
    params = []

    if category is not None:
        conditions.append(f"category = {placeholder}")
        params.append(category)

    if name is not None:
        conditions.append(f"name = {placeholder}")
        params.append(name)

    if name_contains is not None:
        conditions.append(f"LOWER(name) LIKE {placeholder}")
        params.append(f"%{name_contains.lower()}%")

    if min_amount is not None:
        conditions.append(f"amount >= {placeholder}")
        params.append(min_amount)

    if max_amount is not None:
        conditions.append(f"amount <= {placeholder}")
        params.append(max_amount)

    sql = "SELECT id, amount, category, name FROM expenses"

    if conditions:
        sql += " WHERE " + " AND ".join(conditions)

    if sort == "amount_asc":
        sql += " ORDER BY amount ASC"
    elif sort == "amount_desc":
        sql += " ORDER BY amount DESC"
    elif sort == "name_asc":
        sql += " ORDER BY name ASC"
    elif sort == "name_desc":
        sql += " ORDER BY name DESC"
    elif sort == "category_asc":
        sql += " ORDER BY category ASC"
    elif sort == "category_desc":
        sql += " ORDER BY category DESC"
    else:
        sql += " ORDER BY id ASC"

    if limit is not None:
        sql += f" LIMIT {placeholder}"
        params.append(limit)

        if offset is not None:
            sql += f" OFFSET {placeholder}"
            params.append(offset)

    cursor = connection.execute(sql, params)

    expenses = []

    raws = cursor.fetchall()

    for raw in raws:
        result = {}

        result["id"] = raw[0]
        result["amount"] = raw[1]
        result["category"] = raw[2]
        result["name"] = raw[3]

        expenses.append(result)

    connection.close()

    return expenses


def get_expense_by_id(expense_id):
    connection = get_connection()

    if os.getenv("DATABASE_URL"):
        cursor = connection.execute(
            "SELECT id, amount, category, name FROM expenses WHERE id = %s",
            (expense_id,),
        )
    else:
        cursor = connection.execute(
            "SELECT id, amount, category, name FROM expenses WHERE id = ?",
            (expense_id,),
        )

    raw = cursor.fetchone()

    expense = None

    if raw is not None:
        expense = {
            "id": raw[0],
            "amount": raw[1],
            "category": raw[2],
            "name": raw[3],
        }

    connection.close()

    return expense


def calculate_totals_by_category():
    connection = get_connection()

    cursor = connection.execute(
        "SELECT category, SUM(amount) FROM expenses GROUP BY category"
    )

    raw = cursor.fetchall()

    totals = {}

    for category, amount in raw:
        totals[category] = amount

    connection.close()

    return totals


def calculate_total_by_amount():
    connection = get_connection()

    cursor = connection.execute("SELECT COALESCE(SUM(amount), 0) FROM expenses")

    raw = cursor.fetchone()

    total = {"total": raw[0]}

    connection.close()

    return total


def get_largest_expense():
    connection = get_connection()

    cursor = connection.execute(
        "SELECT id, amount, category, name FROM expenses ORDER BY amount DESC, id ASC LIMIT 1"
    )

    raw = cursor.fetchone()

    largest = None

    if raw is not None:
        largest = {}

        largest["id"] = raw[0]
        largest["amount"] = raw[1]
        largest["category"] = raw[2]
        largest["name"] = raw[3]

    connection.close()

    return largest


def update_expense(expense_id, amount, category, name):
    connection = get_connection()

    placeholder = "%s" if os.getenv("DATABASE_URL") else "?"

    if amount is not None:
        connection.execute(
            f"UPDATE expenses SET amount = {placeholder} WHERE id = {placeholder}",
            (amount, expense_id),
        )

    if category is not None:
        connection.execute(
            f"UPDATE expenses SET category = {placeholder} WHERE id = {placeholder}",
            (category, expense_id),
        )

    if name is not None:
        connection.execute(
            f"UPDATE expenses SET name = {placeholder} WHERE id = {placeholder}",
            (name, expense_id),
        )

    connection.commit()

    expense = get_expense_by_id(expense_id)

    connection.close()

    return expense


def delete_expense(expense_id):
    connection = get_connection()

    placeholder = "%s" if os.getenv("DATABASE_URL") else "?"

    cursor = connection.execute(
        f"DELETE FROM expenses WHERE id = {placeholder}",
        (expense_id,),
    )

    connection.commit()

    deleted_count = cursor.rowcount

    connection.close()

    return deleted_count == 1


def delete_expenses():
    connection = get_connection()

    connection.execute("DELETE FROM expenses")

    connection.commit()

    connection.close()

    return True


def count_expenses(
    category=None,
    name=None,
    name_contains=None,
    min_amount=None,
    max_amount=None,
):
    connection = get_connection()

    placeholder = "%s" if os.getenv("DATABASE_URL") else "?"

    conditions = []
    params = []

    if category is not None:
        conditions.append(f"category = {placeholder}")
        params.append(category)

    if name is not None:
        conditions.append(f"name = {placeholder}")
        params.append(name)

    if name_contains is not None:
        conditions.append(f"LOWER(name) LIKE {placeholder}")
        params.append(f"%{name_contains.lower()}%")

    if min_amount is not None:
        conditions.append(f"amount >= {placeholder}")
        params.append(min_amount)

    if max_amount is not None:
        conditions.append(f"amount <= {placeholder}")
        params.append(max_amount)

    sql = "SELECT COUNT(*) FROM expenses"

    if conditions:
        sql += " WHERE " + " AND ".join(conditions)

    total_count = connection.execute(sql, params).fetchone()[0]

    connection.close()

    return total_count
