import os


def migration_1_create_expenses(connection):
    if os.getenv("DATABASE_URL"):
        connection.execute("""
            CREATE TABLE IF NOT EXISTS expenses (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                amount REAL NOT NULL,
                category TEXT NOT NULL,
                name TEXT NOT NULL
            )
        """)
    else:
        connection.execute("""
            CREATE TABLE IF NOT EXISTS expenses (
                id INTEGER PRIMARY KEY,
                amount REAL NOT NULL,
                category TEXT NOT NULL,
                name TEXT NOT NULL
            )
        """)


MIGRATIONS = [
    (1, migration_1_create_expenses),
]


def ensure_migrations_table(connection):
    connection.execute("""
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version INTEGER PRIMARY KEY
        )
    """)


def get_applied_versions(connection):
    rows = connection.execute("SELECT version FROM schema_migrations").fetchall()

    return {row[0] for row in rows}


def run_migrations(connection):
    ensure_migrations_table(connection)

    applied_versions = get_applied_versions(connection)

    for version, migration in MIGRATIONS:
        if version not in applied_versions:
            migration(connection)

            connection.execute(
                f"INSERT INTO schema_migrations (version) VALUES ({version})"
            )

            connection.commit()
